import { NextResponse } from "next/server"
import { createServerClient } from "@/lib/supabase"

export const runtime = "nodejs"

const POSTS = [
  {
    slug: "regularizarse-3-anos-espana",
    title: "¿Puedo regularizarme si llevo más de 3 años en España sin papeles?",
    excerpt: "El arraigo social es la vía más usada, pero tiene condiciones concretas que debes cumplir antes de pedir cita.",
    category: "situacion",
    tags: [],
    content: "<p>Para muchas personas que llevan años viviendo en España sin regularizar su situación, el arraigo social representa la primera —y muchas veces la única— oportunidad real. La ley exige al menos tres años de permanencia continuada en territorio español, acreditada fundamentalmente mediante el padrón municipal.</p><p>Sin embargo, cumplir el requisito temporal no es suficiente. También deberás aportar un informe favorable de integración social emitido por el ayuntamiento o la comunidad autónoma, medios económicos acreditados y los antecedentes penales de todos los países donde hayas residido en los últimos cinco años.</p><h2>¿Cuándo presentar la solicitud?</h2><p>El momento importa. Una solicitud incompleta cuenta como intento y puede complicar el siguiente. Si tienes dudas sobre si realmente cumples los requisitos, consulta antes de pedir la cita. Un expediente bien construido tiene más posibilidades que uno precipitado.</p>",
    published: true,
    featured: true,
    published_at: "2026-01-15T10:00:00Z",
  },
  {
    slug: "arraigo-social-2026-requisitos",
    title: "Arraigo social 2026: todos los requisitos actualizados",
    excerpt: "Desde la reforma de 2023, el arraigo social ha cambiado. Te explicamos qué documentos necesitas hoy, no hace dos años.",
    category: "tramite",
    tags: ["actualizado"],
    content: "<p>El arraigo social es la vía de regularización más solicitada en España, pero también una de las que más confusión genera por los constantes cambios normativos. La reforma de 2023 modificó de forma relevante tanto los requisitos de fondo como la documentación exigida por las delegaciones de gobierno.</p><p>En 2026, para presentar una solicitud de arraigo social necesitas: padrón continuado durante al menos tres años, informe de integración social favorable, contrato de trabajo firmado o acreditación de medios económicos suficientes, pasaporte en vigor, y certificado de antecedentes penales del país de origen debidamente apostillado y traducido.</p><h2>El informe de integración</h2><p>El informe de integración social lo emite el ayuntamiento de tu municipio de empadronamiento. No todos los ayuntamientos lo tramitan con la misma agilidad ni con los mismos criterios. Conocer el procedimiento de tu ciudad antes de solicitarlo puede ahorrarte semanas de espera y preparar mejor la entrevista.</p>",
    published: true,
    featured: false,
    published_at: "2026-02-03T09:00:00Z",
  },
  {
    slug: "errores-frecuentes-arraigo",
    title: "Los 5 errores más frecuentes al pedir arraigo que causan denegación",
    excerpt: "Hemos revisado cientos de expedientes. Estos cinco fallos aparecen siempre y todos son evitables.",
    category: "errores",
    tags: [],
    content: "<p>Después de revisar cientos de expedientes de arraigo social denegados, hay un patrón que se repite: la mayoría de resoluciones negativas no se deben a que la persona no cumpliera los requisitos de fondo, sino a errores concretos y evitables en la presentación del expediente.</p><p>Los cinco errores más frecuentes son: presentar el padrón con interrupciones no justificadas, aportar un contrato de trabajo con cláusulas que no cumplen el salario mínimo, entregar el certificado de antecedentes penales sin apostilla o sin traducción jurada, llevar una foto de documento que no cumple las especificaciones técnicas, y no verificar la vigencia del pasaporte antes de solicitar la cita.</p><h2>El más costoso: el padrón discontinuo</h2><p>Una baja de padrón, aunque sea breve y aunque hayas seguido viviendo en España, puede invalidar el cómputo de tres años. La administración exige continuidad documental, no continuidad real. Un único periodo sin padrón obliga a esperar que vuelva a acumularse el tiempo.</p>",
    published: true,
    featured: false,
    published_at: "2026-01-20T11:00:00Z",
  },
  {
    slug: "familia-colombiana-residencia",
    title: "Cómo conseguimos la residencia para una familia colombiana en situación irregular",
    excerpt: "Llevaban 4 años sin papeles y con dos hijos nacidos en España. Esta es la estrategia que usamos.",
    category: "casos",
    tags: [],
    content: "<p>En 2024 nos llegó el caso de una familia colombiana con dos adultos y dos hijos nacidos en España. Los adultos llevaban más de cuatro años empadronados en el mismo municipio pero nunca habían iniciado el trámite por miedo a la documentación del país de origen.</p><p>La estrategia fue clara: solicitar el arraigo social para ambos adultos de forma simultánea, aprovechando que uno de ellos tenía un preacuerdo de contrato de trabajo. Los menores, al ser ciudadanos españoles, permitían reforzar el informe de integración con vínculos familiares directos.</p><h2>El resultado</h2><p>Nueve meses después de presentar la solicitud, ambos obtuvieron la autorización de residencia y trabajo. Hoy tienen la residencia renovada y uno de ellos ha iniciado la solicitud de larga duración.</p>",
    published: true,
    featured: false,
    published_at: "2025-11-10T10:00:00Z",
  },
  {
    slug: "empleados-hogar-regularizacion",
    title: "España amplía el plazo de regularización para empleados del hogar",
    excerpt: "El Ministerio de Inclusión ha publicado una instrucción que afecta a miles de trabajadores domésticos sin contrato formal.",
    category: "actualidad",
    tags: ["cambio-legal", "aviso"],
    content: "<p>El Ministerio de Inclusión, Seguridad Social y Migraciones ha publicado una instrucción que amplía el margen de regularización para personas que trabajan en el servicio doméstico sin contrato laboral formalizado. La medida afecta principalmente a quienes tienen arraigo social pendiente o en tramitación.</p><p>La instrucción permite que el preacuerdo de contrato para el servicio del hogar pueda ser firmado con hasta noventa días de antelación a la presentación de la solicitud, ampliando el margen anterior de cuarenta y cinco días. Además, aclara que el contrato a tiempo parcial también es válido si supera las veinte horas semanales.</p><h2>¿A quién afecta?</h2><p>La medida afecta a todas las personas con expediente de arraigo social en tramitación cuyo contrato de trabajo sea de empleado de hogar. Si tu solicitud ya fue presentada y el contrato era a tiempo parcial, conviene revisar si la instrucción permite subsanar documentación antes de la resolución.</p>",
    published: true,
    featured: true,
    published_at: "2026-04-22T09:00:00Z",
  },
  {
    slug: "arraigo-social-vs-laboral",
    title: "Arraigo social vs arraigo laboral: cuál te conviene según tu situación",
    excerpt: "No son equivalentes ni en requisitos ni en lo que consigues. La elección equivocada puede costarte años.",
    category: "situacion",
    tags: [],
    content: "<p>El arraigo social y el arraigo laboral son dos vías de regularización distintas, con requisitos diferentes y con resultados también diferentes. La confusión entre ambas es frecuente y puede llevar a presentar la solicitud incorrecta, lo que supone tiempo perdido y, en algunos casos, dificultar la vía correcta.</p><p>El arraigo social requiere tres años de permanencia y un informe de integración social. El arraigo laboral requiere solo dos años de permanencia, pero exige acreditar una relación laboral de al menos seis meses con la misma empresa dentro de esos dos años. Sin esa relación laboral demostrable, el arraigo laboral no es viable.</p><h2>¿Cuál te conviene?</h2><p>Si llevas más de tres años y no tienes relación laboral formal acreditada, el arraigo social es tu vía. Si llevas entre dos y tres años y puedes demostrar trabajo continuado con un solo empleador, el arraigo laboral puede ser más rápido.</p>",
    published: true,
    featured: false,
    published_at: "2025-12-08T10:00:00Z",
  },
  {
    slug: "renovar-tie-caducado",
    title: "Renovar el TIE cuando ha caducado: plazos, consecuencias y cómo actuar",
    excerpt: "La tarjeta caducada no significa que tu autorización haya expirado, pero actuar a tiempo evita problemas serios.",
    category: "tramite",
    tags: ["actualizado"],
    content: "<p>El TIE (Tarjeta de Identidad de Extranjero) es el documento físico que acredita tu autorización de residencia. Su caducidad no equivale a la caducidad de la residencia en sí, pero sí genera problemas prácticos: no puedes usarla como documento de identidad válido, algunos empleadores la exigen vigente y ciertos trámites administrativos la requieren en vigor.</p><p>El plazo para solicitar la renovación de la tarjeta es de un mes antes de su fecha de caducidad. Si ya ha caducado, puedes solicitarla igualmente, aunque en algunos casos se exigirá justificar el retraso.</p><h2>Si ya caducó</h2><p>Si tu TIE ha caducado, presenta la solicitud cuanto antes y guarda el justificante de cita o de presentación. Ese justificante actúa como documento acreditativo mientras esperas la nueva tarjeta. No esperes a que el empleador o un organismo te lo recuerde.</p>",
    published: true,
    featured: false,
    published_at: "2026-03-01T09:00:00Z",
  },
  {
    slug: "error-del-plazo-extranjeria",
    title: "El error del plazo: por qué una semana puede costarte la residencia",
    excerpt: "En extranjería los plazos son duros. Un expediente caducado no se reactiva: empieza de cero.",
    category: "errores",
    tags: ["aviso"],
    content: "<p>En el derecho administrativo español, los plazos son plazos. No hay margen de gracia ni posibilidad de reactivar un expediente que ha caducado por inactividad. Esta rigidez afecta de forma especialmente grave a los trámites de extranjería, donde los plazos se cuentan en días hábiles y los errores cuestan meses o años.</p><p>El error más habitual: no presentar la documentación requerida dentro del plazo de subsanación. Cuando la administración te pide documentos adicionales, tienes un plazo concreto. Si no cumples ese plazo, el expediente se archiva. No se puede recurrir por haber llegado tarde.</p><h2>Cómo evitarlo</h2><p>Cuando presentes cualquier solicitud de extranjería, anota en el calendario la fecha de presentación y suma noventa días. Si en ese tiempo no recibes respuesta ni requerimiento, acude a verificar el estado del expediente. En extranjería, la proactividad es parte del trámite.</p>",
    published: true,
    featured: false,
    published_at: "2026-02-18T10:00:00Z",
  },
  {
    slug: "venezolana-arraigo-8-meses",
    title: "Residencia obtenida en 8 meses para una venezolana con arraigo social",
    excerpt: "Sin trabajo formal ni contratos previos, pero con padrón continuo y vínculos familiares. Así lo resolvimos.",
    category: "casos",
    tags: [],
    content: "<p>María llegó a España en 2019 procedente de Caracas. En 2023 nos contactó para gestionar su regularización. No tenía trabajo formal, nunca había cotizado y su única documentación era el padrón municipal continuo desde su llegada y varios certificados de cursos de formación realizados en el municipio.</p><p>El informe de integración social fue la clave. El ayuntamiento de su municipio tenía un protocolo de entrevista estructurado, y el trabajo previo para preparar la documentación de integración resultó determinante para que el informe saliera favorable.</p><h2>El contrato</h2><p>Una semana antes de presentar la solicitud, conseguimos que un comercio local firmara el preacuerdo de contrato. La resolución llegó ocho meses después: favorable. Hoy María trabaja regularizada y ha iniciado los trámites para reagrupar a su hija menor.</p>",
    published: true,
    featured: false,
    published_at: "2025-10-15T10:00:00Z",
  },
  {
    slug: "reagrupacion-familiar-2026",
    title: "Nueva normativa de reagrupación familiar: lo que cambia en 2026",
    excerpt: "Requisitos de ingresos actualizados, nuevos plazos de resolución y qué ocurre con los menores.",
    category: "actualidad",
    tags: ["cambio-legal"],
    content: "<p>La reagrupación familiar es uno de los trámites de extranjería más solicitados y también uno de los que más ha cambiado en los últimos años. En 2026, la actualización del umbral de ingresos mínimos exigidos al reagrupante y la revisión de los plazos de resolución afectan a miles de expedientes en curso y por presentar.</p><p>A partir de enero de 2026, el umbral de ingresos mínimos para reagrupar al cónyuge o pareja se calcula sobre el IPREM vigente más un porcentaje por cada miembro adicional. El importe ha subido respecto a 2024 como consecuencia de la actualización del IPREM.</p><h2>Plazos de resolución</h2><p>El reglamento establece un plazo máximo de tres meses para resolver. En la práctica, las delegaciones más saturadas siguen superándolo. Si tu expediente supera ese plazo, puedes interponer recurso por silencio administrativo negativo, lo que abre la vía contenciosa sin necesidad de esperar indefinidamente.</p>",
    published: true,
    featured: true,
    published_at: "2026-05-02T09:00:00Z",
  },
  {
    slug: "arraigo-denegado-dos-veces",
    title: "Me han denegado el arraigo dos veces. ¿Qué puedo hacer?",
    excerpt: "Una denegación no es el final, pero sí una señal de que algo en el expediente falla. Aquí qué hacer.",
    category: "situacion",
    tags: [],
    content: "<p>Recibir una denegación de arraigo es frustrante. Recibirla dos veces genera una sensación de bloqueo difícil de gestionar. Sin embargo, la doble denegación no implica una inhabilitación: no existe en la ley española un límite de solicitudes de arraigo, siempre que se presenten con un expediente diferente y con fundamento.</p><p>Lo primero que hay que hacer ante una segunda denegación es leer la resolución con atención. La administración debe motivar su decisión. Si la motivación es concreta —falta de integración, padrón discontinuo, contrato inválido— hay que corregir ese punto antes de volver a intentarlo.</p><h2>Cuándo volver a intentarlo</h2><p>Si la denegación fue por falta de tiempo de padrón o por un informe de integración desfavorable, esperar y reconstruir el expediente suele ser más eficaz que recurrir. Si la denegación fue por un error formal subsanable, el recurso es el camino.</p>",
    published: true,
    featured: false,
    published_at: "2025-09-22T10:00:00Z",
  },
  {
    slug: "cuenta-ajena-guia-2026",
    title: "Autorización de trabajo por cuenta ajena: guía completa 2026",
    excerpt: "Qué necesita el empresario, qué necesitas tú y cómo coordinar la solicitud para que no fracase.",
    category: "tramite",
    tags: ["actualizado"],
    content: "<p>La autorización de residencia y trabajo por cuenta ajena es el trámite que permite a una empresa contratar legalmente a una persona extranjera que no tiene residencia en España. Es una de las vías de entrada legal al mercado de trabajo más utilizadas, pero también una de las que más errores presenta por la coordinación que requiere entre empresa y trabajador.</p><p>El empresario debe demostrar que la oferta de empleo existe realmente, que la empresa está al corriente con la Seguridad Social y con Hacienda, y que ha realizado una búsqueda previa en el mercado de trabajo español sin encontrar candidatos adecuados.</p><h2>Qué aporta el trabajador</h2><p>El trabajador debe aportar pasaporte, título o certificado de estudios si el puesto lo requiere, y en algunos casos una acreditación de experiencia laboral. La solicitud la presenta el empresario, pero la autorización se la conceden a la persona trabajadora.</p>",
    published: true,
    featured: false,
    published_at: "2026-01-30T10:00:00Z",
  },
  {
    slug: "contrato-trabajo-invalido-arraigo",
    title: "Por qué tu contrato de trabajo puede no valer para el arraigo",
    excerpt: "No todos los contratos son válidos. Los empleadores informales y los contratos a tiempo parcial tienen reglas propias.",
    category: "errores",
    tags: [],
    content: "<p>El contrato de trabajo es uno de los documentos centrales del arraigo social: sin él, o con uno inválido, la solicitud se deniega. Sin embargo, muchos expedientes llegan con contratos que la administración rechaza por razones que podrían haberse evitado con una revisión previa.</p><p>Los contratos más frecuentemente rechazados son: contratos firmados por empresas con deudas con la Seguridad Social, contratos a tiempo parcial con menos de veinte horas semanales, y contratos firmados por apoderados sin que se acredite la representación.</p><h2>La verificación previa</h2><p>Antes de presentar la solicitud, comprueba que la empresa que firma el contrato está al corriente con la Seguridad Social. Puedes pedirle un certificado de estar al corriente de pago. Un contrato inválido no solo causa la denegación: también puede generar consecuencias para el empresario.</p>",
    published: true,
    featured: false,
    published_at: "2025-08-14T10:00:00Z",
  },
  {
    slug: "reagrupacion-menor-marroqui",
    title: "Reagrupación familiar de menor cuando el padre tiene residencia temporal",
    excerpt: "La reagrupación de hijos menores tiene sus propias condiciones. Este caso con un padre marroquí lo ilustra bien.",
    category: "casos",
    tags: [],
    content: "<p>Karim nos contactó en 2024. Llevaba tres años en España con residencia temporal por trabajo y quería reagrupar a su hijo de nueve años que vivía con la madre en Marruecos. El menor viajaría solo bajo la custodia del padre, y eso generaba una serie de exigencias documentales adicionales.</p><p>Para reagrupar a un menor con un solo progenitor residente en España es necesario acreditar que se tiene la guardia y custodia del menor o el consentimiento del otro progenitor, que se dispone de vivienda adecuada, y que los ingresos superan el umbral exigido. En el caso de Karim, la madre firmó un documento notarial de consentimiento apostillado desde Marruecos.</p><h2>El resultado</h2><p>El expediente tardó cinco meses en resolverse. La reagrupación fue concedida. El menor viajó con visado de reagrupación y quedó empadronado en España.</p>",
    published: true,
    featured: false,
    published_at: "2025-07-30T10:00:00Z",
  },
  {
    slug: "reglamento-extranjeria-cambios-2026",
    title: "Cambios en el reglamento de extranjería en 2026: resumen ejecutivo",
    excerpt: "El BOE publicó modificaciones importantes. Aquí solo lo que afecta a las solicitudes más habituales.",
    category: "actualidad",
    tags: ["cambio-legal"],
    content: "<p>El reglamento de extranjería —Real Decreto 557/2011— ha sido modificado en varias ocasiones desde su aprobación. En 2026, una nueva modificación afecta a tres áreas concretas: los plazos de resolución de reagrupación familiar, los requisitos de ingresos para la renovación de residencia, y las condiciones del arraigo laboral.</p><p>En el arraigo laboral, la modificación más relevante es la aclaración de qué tipo de vínculos laborales cuentan para acreditar los seis meses de relación con el mismo empleador. Ahora se aceptan expresamente las relaciones de servicio doméstico acreditadas por testigos y certificados municipales.</p><h2>Para renovaciones</h2><p>En renovaciones de residencia temporal, se flexibiliza el requisito de cotización mínima para personas que hayan trabajado con contrato y hayan cotizado al menos la mitad del período de la autorización. Esta flexibilización afecta especialmente a personas con períodos de baja laboral o desempleo.</p>",
    published: true,
    featured: false,
    published_at: "2026-03-15T09:00:00Z",
  },
  {
    slug: "trabajar-mientras-espero-resolucion",
    title: "¿Puedo trabajar mientras espero la resolución del arraigo?",
    excerpt: "Depende del momento del proceso en que estés. Hay una ventana legal que la mayoría no conoce.",
    category: "situacion",
    tags: [],
    content: "<p>Una de las preguntas más frecuentes: ¿puedo trabajar mientras el arraigo está en tramitación? La respuesta corta es: depende. La respuesta larga requiere distinguir dos momentos del proceso.</p><p>Durante la tramitación ordinaria del arraigo social, no tienes autorización de trabajo. Sin embargo, una vez que recibes la resolución favorable —aunque todavía no hayas recogido la tarjeta— sí puedes trabajar, porque la autorización tiene efectos desde la fecha de la resolución.</p><h2>La ventana de renovación</h2><p>Si has presentado la solicitud de renovación antes de que caduque tu autorización, tienes derecho a continuar trabajando durante todo el período de tramitación, aunque tu tarjeta aparezca como caducada. El justificante de presentación de la renovación es el documento que lo acredita ante el empleador.</p>",
    published: true,
    featured: false,
    published_at: "2025-06-20T10:00:00Z",
  },
  {
    slug: "tarjeta-familiar-ue",
    title: "Tarjeta de familiar de ciudadano UE: quién puede pedirla y cómo",
    excerpt: "Si tu pareja o cónyuge tiene ciudadanía europea, tienes una vía de regularización más rápida que el arraigo.",
    category: "tramite",
    tags: ["actualizado"],
    content: "<p>La tarjeta de residencia de familiar de ciudadano de la Unión Europea es una de las vías de regularización más potentes y menos conocidas. Permite regularizarse a personas sin importar cuánto tiempo lleven en España, siempre que el familiar comunitario resida efectivamente en España.</p><p>Pueden solicitarla el cónyuge o pareja registrada del ciudadano UE, los descendientes menores de 21 años, los ascendientes a cargo, y otros familiares que se encuentren a cargo del ciudadano UE. El ciudadano UE puede ser de cualquier estado miembro: no tiene que ser español.</p><h2>Requisitos clave</h2><p>El ciudadano UE debe estar inscrito en el Registro Central de Extranjeros o tener el certificado de registro. No se exige un mínimo de tiempo de permanencia en España ni un contrato de trabajo del solicitante: los requisitos económicos los aporta el ciudadano UE.</p>",
    published: true,
    featured: false,
    published_at: "2026-02-25T10:00:00Z",
  },
  {
    slug: "certificado-empadronamiento-errores",
    title: "Certificado de empadronamiento: los errores que no se pueden cometer",
    excerpt: "El padrón puede hacer o deshacer un expediente. Dirección incorrecta, fechas inconsistentes, períodos discontinuos.",
    category: "errores",
    tags: ["aviso"],
    content: "<p>El certificado de empadronamiento es el documento más importante de cualquier expediente de arraigo. Sin embargo, muchas personas lo aportan sin revisarlo con atención y descubren el problema solo cuando la administración envía un requerimiento o, peor, una resolución desfavorable.</p><p>Los errores más frecuentes: aportar el certificado de padrón actual en lugar del histórico, aportar un padrón histórico que muestra una baja aunque sea breve, y aportar un padrón en el que el domicilio no coincide con el que consta en otros documentos del expediente.</p><h2>Antes de presentar</h2><p>Pide el padrón histórico en tu ayuntamiento y revísalo antes de incluirlo en el expediente. Comprueba que las fechas son continuas y que el domicilio es el mismo que figura en el contrato y en los demás documentos. Si hay discrepancias, corrígelas antes de pedir la cita: después es tarde.</p>",
    published: true,
    featured: false,
    published_at: "2025-05-10T10:00:00Z",
  },
  {
    slug: "arraigo-laboral-electricista",
    title: "Arraigo laboral en 6 meses: el caso de un electricista ecuatoriano",
    excerpt: "Tenía relación laboral real pero sin contrato escrito. Construimos el expediente desde las cotizaciones y testigos.",
    category: "casos",
    tags: [],
    content: "<p>Rodrigo llevaba dos años trabajando como electricista para el mismo autónomo en Barcelona. No tenía contrato escrito: el acuerdo era verbal y el pago en efectivo. Sin embargo, el autónomo sí le había dado de alta en la Seguridad Social en varios períodos, lo que dejaba un rastro documental en la vida laboral.</p><p>Con esos datos construimos el expediente de arraigo laboral. La vida laboral mostraba períodos de alta con el mismo empresario que superaban los seis meses. El empresario firmó una carta de reconocimiento de la relación laboral y dos compañeros firmaron declaraciones como testigos.</p><h2>La resolución</h2><p>El expediente tardó seis meses en resolverse. La resolución fue favorable. Rodrigo obtuvo la autorización de residencia y trabajo. Es un caso que ilustra que la falta de contrato escrito no siempre bloquea el arraigo laboral si hay cotizaciones reales.</p>",
    published: true,
    featured: false,
    published_at: "2025-04-18T10:00:00Z",
  },
  {
    slug: "cita-previa-extranjeria-2026",
    title: "Cita previa en extranjería: el método que más funciona en 2026",
    excerpt: "La cita escasea pero no es imposible conseguirla. Aquí la estrategia que usamos con nuestros clientes.",
    category: "tramite",
    tags: ["aviso"],
    content: "<p>Conseguir cita previa en las oficinas de extranjería es, para muchas personas, el primer obstáculo real del trámite. El sistema de cita previa del Ministerio del Interior libera plazas de forma discontinua y en horarios variables, lo que hace que muchas personas lleven semanas intentándolo sin éxito.</p><p>En 2026 la situación no ha mejorado en las provincias más saturadas —Madrid, Barcelona, Valencia y Málaga son las más complicadas—. Sin embargo, hay patrones que facilitan el acceso: las plazas suelen liberarse entre las 8:00 y las 9:00 de la mañana de lunes a jueves, con picos a principios de mes.</p><h2>Alternativas si no consigues cita</h2><p>Si llevas más de tres meses sin conseguir cita para presentar una solicitud urgente, puedes presentar la documentación por registro general de entrada en la Delegación del Gobierno. No es la vía preferida, pero es válida y deja constancia de la fecha de presentación, que es lo que importa para los plazos.</p>",
    published: true,
    featured: false,
    published_at: "2026-04-05T09:00:00Z",
  },
  {
    slug: "nie-tie-due-diferencias",
    title: "NIE, TIE y DUE: qué es cada documento y para qué sirve realmente",
    excerpt: "La confusión entre estos tres documentos es constante. Un error al pedirlos puede retrasar todo el proceso.",
    category: "situacion",
    tags: ["actualizado"],
    content: "<p>El NIE (Número de Identificación de Extranjero), el TIE (Tarjeta de Identidad de Extranjero) y el DUE (Documento Único Electrónico) son tres cosas diferentes que la gente suele confundir porque los tres identifican a personas extranjeras en España.</p><p>El NIE es simplemente un número permanente que no caduca. El TIE es el documento físico —la tarjeta— que acredita la residencia legal en España e incluye el NIE. El DUE es el documento que obtienen los ciudadanos de la UE que se registran en España: sustituye al TIE para los comunitarios.</p><h2>¿Cuál necesitas?</h2><p>Si eres ciudadano extracomunitario y tienes o vas a obtener residencia en España, necesitas un TIE. Si eres ciudadano de un país de la UE y vas a residir en España más de tres meses, necesitas el DUE. Si solo necesitas un número para una compra inmobiliaria o apertura de cuenta bancaria, con el NIE puro puede ser suficiente.</p>",
    published: true,
    featured: false,
    published_at: "2026-01-08T10:00:00Z",
  },
  {
    slug: "modelo-790-errores-frecuentes",
    title: "Modelo 790: errores que invalidan tu solicitud de residencia",
    excerpt: "Código de tasa incorrecto, importe desactualizado, IBAN mal transcrito. La administración no avisa: devuelve.",
    category: "errores",
    tags: [],
    content: "<p>El modelo 790 es el impreso de autoliquidación de tasas de la Secretaría de Estado de Migraciones. Sin él, o con él mal cumplimentado, ninguna solicitud de residencia se admite a trámite. Es uno de los pasos más mecánicos del proceso, pero también uno de los que más errores genera.</p><p>Los errores más frecuentes: usar el código de tasa incorrecto, pagar un importe desactualizado porque los importes varían cada año, y pagar desde una cuenta cuyo titular no coincide con el nombre del solicitante.</p><h2>Cómo hacerlo bien</h2><p>Descarga siempre el modelo 790 desde la web oficial del Ministerio del Interior, no de páginas de terceros. Verifica el código de tasa específico para tu tipo de solicitud y el importe vigente para el año en curso. Paga desde tu propia cuenta bancaria y guarda el justificante con el nombre del solicitante anotado.</p>",
    published: true,
    featured: false,
    published_at: "2025-03-22T10:00:00Z",
  },
  {
    slug: "padron-municipal-critico",
    title: "Cuándo el padrón municipal puede salvar o hundir tu expediente",
    excerpt: "La continuidad del padrón es tan importante como los años que llevas en España. Un lapso puede anularlo todo.",
    category: "errores",
    tags: ["aviso"],
    content: "<p>El padrón municipal es mucho más que un trámite burocrático: es la prueba principal de que llevas el tiempo exigido en España. Para el arraigo social, necesitas demostrar tres años continuados. Cualquier interrupción en el padrón —aunque hayas seguido viviendo en España— puede invalidar el cómputo.</p><p>La situación más peligrosa: un cambio de domicilio sin actualizar el padrón a tiempo. Si te mudas y tardas varios meses en empadronarte en el nuevo domicilio, puede aparecer un período sin padrón en el histórico. La administración interpreta esa laguna como una ausencia de España.</p><h2>Cómo protegerte</h2><p>Si vas a cambiar de domicilio, tramita el nuevo empadronamiento antes o el mismo día que te mudas. Si ya tienes un período sin padrón en el histórico, consulta si es posible acreditarlo con documentación alternativa: facturas de suministros, recibos bancarios o atenciones sanitarias del período en cuestión.</p>",
    published: true,
    featured: false,
    published_at: "2025-12-01T10:00:00Z",
  },
  {
    slug: "reagrupacion-abuelos-dependientes",
    title: "Reagrupación familiar de abuelos mayores dependientes: cómo se tramita",
    excerpt: "Los ascendientes mayores tienen requisitos especiales. El caso de una familia peruana que lo consiguió.",
    category: "casos",
    tags: [],
    content: "<p>La reagrupación de ascendientes —padres, abuelos— es la modalidad más exigente de reagrupación familiar. El residente en España necesita tener residencia de larga duración o al menos la segunda renovación de residencia temporal, además de acreditar ingresos significativamente superiores a los exigidos para reagrupar cónyuge o hijos.</p><p>El caso de la familia Quispe ilustra el proceso. El hijo mayor, con larga duración y trabajo estable, quería traer a sus padres de 72 y 68 años desde Lima. Los padres no tenían ingresos propios y dependían económicamente de él. Ese vínculo de dependencia económica hay que acreditarlo documentalmente: transferencias al exterior, cartas de dependencia y certificados médicos.</p><h2>El resultado</h2><p>El proceso duró ocho meses. La documentación económica fue revisada dos veces por la delegación. Finalmente la reagrupación fue concedida. Los padres llegaron con visado de reagrupación y quedaron empadronados en Madrid.</p>",
    published: true,
    featured: false,
    published_at: "2025-02-14T10:00:00Z",
  },
  {
    slug: "resoluciones-expres-arraigo",
    title: "¿Hay resoluciones exprés de arraigo? Lo que dicen los datos reales",
    excerpt: "Hay oficinas con plazos de 3 meses y otras con 18. La dispersión es enorme y no siempre se publicita.",
    category: "actualidad",
    tags: [],
    content: "<p>Una de las preguntas más frecuentes antes de presentar un arraigo es: ¿cuánto tarda? La respuesta honesta es: depende de la delegación. No existe una respuesta única porque los plazos de resolución varían enormemente según la oficina gestora, y esa variación no siempre se refleja en las estadísticas oficiales.</p><p>Los datos que manejamos de expedientes gestionados en los últimos dos años muestran un rango que va de tres meses en algunas provincias pequeñas a dieciocho meses en las delegaciones de Madrid y Barcelona. El plazo legal máximo es de tres meses, pero el incumplimiento es la norma en las zonas más saturadas.</p><h2>¿Hay forma de agilizar?</h2><p>No existe un procedimiento exprés oficial para el arraigo. Lo que sí existe es la posibilidad de interponer recurso por silencio administrativo negativo cuando el plazo de tres meses ha vencido. En algunos casos, esa presión formal acelera la resolución. La decisión de recurrir o esperar depende del plazo real de la delegación y de la situación laboral de la persona.</p>",
    published: true,
    featured: false,
    published_at: "2025-01-30T10:00:00Z",
  },
]

export async function GET() {
  if (process.env.NODE_ENV !== "development") {
    return NextResponse.json({ error: "Solo disponible en desarrollo" }, { status: 403 })
  }

  const supabase = createServerClient()

  const slugs = POSTS.map(p => p.slug)
  await supabase.from("blog_posts").delete().in("slug", slugs)

  const { error } = await supabase.from("blog_posts").insert(POSTS)
  if (error) {
    console.error("Seed error:", error)
    return NextResponse.json({ error: error.message }, { status: 500 })
  }

  return NextResponse.json({ ok: true, count: POSTS.length })
}
